List<String> dataRekening = [
  'Uang Tunai',
  'Seabank',
  'BRI (Bank Rakyat Indonesia)',
  'BCA (Bank Central Asia)',
  'BNI (Bank Negara Indonesia)',
  'Mandiri',
  'CIMB Niaga',
  'Danamon',
  'BTN (Bank Tabungan Negara)',
  'Permata Bank',
  'OCBC NISP',
  'Bank Jago',
  'Bank Mega',
  'Panin Bank',
  'Maybank',
  'BRI Syariah',
  'Mandiri Syariah',
  'BSI (Bank Syariah Indonesia)',
  'BTPN (Jenius)',
  'Digibank by DBS',
  'Blu by BCA Digital',
  'Line Bank',
  'Bank DKI',
  'Bank BJB',
  'Bank Jateng',
  'Bank Jatim',
  'Dana',
  'OVO',
  'GoPay',
  'ShopeePay',
  'LinkAja',
  'Lainnya',
];
