import 'package:flutter/material.dart';

final List<Map<String, dynamic>> newDataTransaction = [
  {
    'title': 'Belanja Bulanan',
    'category': 'Kebutuhan Rumah',
    'nominal': 750000,
    'icon': Icons.shopping_cart,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 27),
  },
  {
    'title': 'Gaji',
    'category': 'Pemasukan',
    'nominal': 5000000,
    'icon': Icons.attach_money,
    'type': 'pemasukan',
    'date': DateTime(2025, 6, 27),
  },
  {
    'title': 'Ngopi',
    'category': 'Hiburan',
    'nominal': 35000,
    'icon': Icons.local_cafe,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 27),
  },
  {
    'title': 'Langganan Netflix',
    'category': 'Langganan',
    'nominal': 149000,
    'icon': Icons.movie,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 28),
  },
  {
    'title': 'Bayar Listrik',
    'category': 'Tagihan',
    'nominal': 420000,
    'icon': Icons.electric_bolt,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 28),
  },
  {
    'title': 'Isi Pulsa',
    'category': 'Telekomunikasi',
    'nominal': 50000,
    'icon': Icons.phone_android,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 28),
  },
  {
    'title': 'Makan Siang',
    'category': 'Makanan',
    'nominal': 30000,
    'icon': Icons.fastfood,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 29),
  },
  {
    'title': 'Transportasi',
    'category': 'Transport',
    'nominal': 25000,
    'icon': Icons.directions_car,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 29),
  },
  {
    'title': 'Donasi',
    'category': 'Sosial',
    'nominal': 100000,
    'icon': Icons.volunteer_activism,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 29),
  },
  {
    'title': 'Belanja Online',
    'category': 'Hiburan',
    'nominal': 250000,
    'icon': Icons.shopping_bag,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 29),
  },
  {
    'title': 'Bonus Project',
    'category': 'Pemasukan',
    'nominal': 1500000,
    'icon': Icons.wallet,
    'type': 'pemasukan',
    'date': DateTime(2025, 6, 30),
  },
  {
    'title': 'Investasi Saham',
    'category': 'Pemasukan',
    'nominal': 200000,
    'icon': Icons.trending_up,
    'type': 'pemasukan',
    'date': DateTime(2025, 6, 30),
  },
  {
    'title': 'Beli Buku',
    'category': 'Pendidikan',
    'nominal': 80000,
    'icon': Icons.menu_book,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 30),
  },
  {
    'title': 'Jual Barang Bekas',
    'category': 'Pemasukan',
    'nominal': 300000,
    'icon': Icons.sell,
    'type': 'pemasukan',
    'date': DateTime(2025, 6, 30),
  },
  {
    'title': 'Streaming Musik',
    'category': 'Langganan',
    'nominal': 49000,
    'icon': Icons.music_note,
    'type': 'pengeluaran',
    'date': DateTime(2025, 6, 30),
  },
];
